- src/views/HomeView.vue
Hey Ihr beiden ich mach kurz nen Test :)
> Test: Martin

- src/App.vue
- src/main.js
- src/router/index.js
- src/styles/chota.css
- src/styles/normalize.css
- src/styles/simple.css
- src/views/HomeView.vue
- src/views/WishList.vue
- src/views/dj/ChangeProfil.vue
- src/views/dj/DjLogin.vue
- src/views/dj/DjOverview.vue
- src/views/dj/DjRegister.vue
- src/views/dj/EditPlaylist.vue
- src/views/dj/EventsView.vue
- src/views/dj/PlaylistsView.vue
- src/views/guest/GuestOverview.vue
- src/views/guest/GuestStart.vue
- src/views/guest/WishSong.vue
> 19 ordnerstruktur

- src/components/QrCodeGenerator.vue
- src/views/dj/CreateEvent.vue
Man kann den QR Code über: rechts klick, dann Bild speichern "runterladen" auf den Laptop. Reicht es?
Ansonsten schaue ich mal, ob man extra dafür noch einen Button einarbeiten kann.
> feat: add component to create a QR code

- src/stores/PlaylistStore.js
- src/styles/chota.css
Habe ein Beispiel State mit Pinia erstellt.
> States with pinia

- src/App.vue
- src/views/dj/CreateEvent.vue
> 42 select eventtype with radiobuttons

- README-Devs.txt
- jsonData/db.json
- src/stores/AppData.js
- src/views/dj/DjOverview.vue
Ein paar Wortänderungen (DE > EN)
> Just to test things

- src/views/dj/DjRegister.vue
> feat: create User

- src/views/dj/DjLogin.vue
- src/views/dj/DjOverview.vue
ACHTUNG: 
Login mit "maadin"
Hat noch keine Api Anbindung!
> 62 loggin in as a user

- src/stores/DjStore.js
- src/views/dj/DjLogin.vue
- src/views/dj/DjRegister.vue
Damit sollte man den PiniaStore besser erweitern können.
> update: piniaStore

- src/views/guest/GuestOverview.vue
- src/views/guest/GuestStart.vue
Gast kann sich einloggen, Daten werden im local Storage gespeichert und Gast wird weiter zu Gast Übersicht navigiert.
> feat: guest is able to log in

- src/views/guest/GuestStart.vue
Ein gast kann sich nur einmal mit einem Namen anmelden. Kommt der Gast wiederholt auf die Start Seite, so wird er direkt zur Overview geleitet.
> fix: login code validiert

- src/components/ActiveDj.vue
- src/components/FileReaderCsv.vue
- src/components/InitDj.js
- src/stores/DjStore.js
- src/views/dj/CreatePlaylist.vue
- src/views/dj/DjLogin.vue
- src/views/dj/DjOverview.vue
- src/views/dj/DjRegister.vue
Ein 
`import { initDj } from '@/components/InitDj'`
und
```
mounted() {
initDj()
}
```
auf jeder DjView sorgen für einen Reload des active Users
> feat: Dj im LocalStorage

- src/components/ActiveDj.vue
- src/components/InitDj.js
- src/stores/DjStoreLars.js
- src/stores/PlaylistStore.js
- src/views/dj/DjRegister.vue
- src/views/dj/EditProfile.vue
- src/views/dj/PlaylistsView.vue
Bitte einmal morgen. Ich habe zunächst einen DJStoreLars angelegt, damit ich im Hauptstore nix kaputt mache.
Können wir später zusammenlegen. 
Die Ausgabe zeigt bisher nur alle User, hier fehlt noch die Logik, es abhängig vom eingeloggten ActiveDj auf den einen Eintrag zu reduzieren. Also bitte den Branch noch nicht löschen, bin noch dran - ist ein Zwischenstand.
> feat: fetch Api Data via new Pinia Store, ciew in edit profile

- src/views/guest/WishSong.vue
Code muss noch später angepasst werden, wenn man die Events erstellen kann und der playlist störe steht...
Aber schon mal die ersten steps hier.
> playlist wird gast beim wünschen als vorschlag angezeigt

- src/stores/DjStore.js
- src/stores/PlaylistStore.js
- src/views/dj/CreatePlaylist.vue
- src/views/dj/EditPlaylist.vue
- src/views/dj/PlaylistsView.vue
Wir können dann jetzt Playlisten auch löschen :)
> 112 function to delete playlists

- src/stores/DjStore.js
- src/views/dj/EditProfile.vue
Eine erste Version des Updaten geht schon mal.
Es sind noch ein paar Punkte offen.
Es werden grad nur Felder die ausgefüllt werden geupdatet und die anderen quasi leer überschrieben.
> Feat: UpdateUserData

- src/views/dj/EditProfile.vue
Schneller fix fürs Profilupdate. 
Es wird gleich beim mount die UpdateData angelegt.
> update: AllDataUpdated

- src/views/dj/CreateEvent.vue
Event kann in die Api hinzugefügt werden.
> 70 1 create event view

- src/App.vue
- src/views/dj/DjLogin.vue
- src/views/guest/WishSong.vue
der Header läuft über eine Direktive style und muss noch im State abgelegt werden bzw. entsprechend geladen werden.
> fix: fixing the logout button and adding background image

- src/views/guest/WishSong.vue
Ich habe das Feld in eine Tabelle umgebaut, so ist es semantisch etwas besser und für Dark and Lightmode gestylt.
> chore: styling for suggestion

- src/views/WishList.vue
Ich hab die WishList optisch ein wenig überarbeitet und das Markup geändert.
> chore: styling, markup

- src/components/PreviewCSV.vue
- src/stores/PlaylistStore.js
- src/views/dj/EditPlaylist.vue
- src/views/dj/PlaylistsView.vue
Ich habe die Speicherung von query params in pinia und den localstorage verschoben.
Auch der Seitenreload funktioniert so. Das könnte man als Vorlage für event bearbeiten nehmen.
> feat: change query param to Pinia State and localstorage

- src/stores/EventStore.js
- src/views/dj/CreateEvent.vue
- src/views/dj/EditEvent.vue
- src/views/dj/EventsView.vue
Ich habe mich vertan mit der Benennung. Statt das Profil zu bearbeiten habe ich EditEvent und so bearbeitet. 
Die Idee mit /events und den Hintergrundbildern bei den Events finde ich super, würde das noch - wenns recht ist ein wenig umstylen, aber dass es in der Übersicht sichtbar ist, ist klasse.
> feat: add function to edit events.

- src/App.vue
- src/stores/EventStore.js
- src/views/HomeView.vue
- src/views/dj/EventsView.vue
Kleines Feature um unsere Bedienung zu erleichtern.
> feat: start-event-dropdown

- src/App.vue
- src/stores/EventStore.js
- src/views/dj/EditEvent.vue
- src/views/dj/EventsView.vue
Sorry Martin, ich habe die Sichtbarkeit der Texte erhöht. Ich hoffe das ist okay so. Es wäre auch gut wenn wir nach dem Prinzip von picocss arbeiten, also in dem "Style" bleiben.
> chore: increase readability

- src/views/dj/EditEvent.vue
- src/views/dj/EditProfile.vue
Nur eine kleine Ergänzung. Wir müssen schauen, wo der Spinner Sinn ergibt, ist also erstmal exemplarisch :)
> feat: add spinner

- src/components/QrCodeGenerator2.vue
- src/views/WishList.vue
- src/views/guest/GuestOverview.vue
- src/views/guest/WishSong.vue
Das ist erstmal das Basic Feature.
die wunsch-grüßen von mehreren gästen habe ich noch nicht mit drin, wenn zb. der gleiche songwunsch + grüße, gesendet wird.
> feat: requests für das aktive event werden angezeigt

- src/views/WishList.vue
> feat: ad dynamic likes

- src/styles/custom-pico.css
- src/views/dj/EditEvent.vue
- src/views/dj/EditPlaylist.vue
- src/views/dj/EditProfile.vue
- src/views/dj/EventsView.vue
- src/views/dj/PlaylistsView.vue
Ich habe die EditProfil View geändert, funktioniert jetzt genauso wie die anderen, ich habe noch ein paar Styles ergänzt und das Default Bild repariert, beim EditEvent.
> fix: change editProfile, add some styles, fix EditEvent (default Image)

- src/styles/custom-pico.css
- src/views/dj/CreateEvent.vue
- src/views/dj/EditEvent.vue
Bild kleiner, paar überflüssige Labels raus
> 180 eventbild scalieren

- src/views/WishList.vue
die buttons abspielen und ablehnen sowie messages und name sind für den gast hidden.
bitte nicht schließen.
> 147 guest wishlist

- src/components/ActiveDj.vue
- src/views/WishList.vue
- src/views/dj/EventsView.vue
- src/views/guest/WishSong.vue
feat: anonym setzen; ablehnen = Wunsch löschen
> 186 dj wishlist view

- src/styles/custom-pico.css
- src/views/WishList.vue
Ich habe die Farben nochmal angepasst, sorry Martin, ich würde gerne so nah an den ursprünglichen Farben bleiben wie möglich. Ich habe sonst noch das Grid angepasst, details gegen article getauscht, line-clamp beim Titel eingestellt und so kosmetische Dinge erledigt.
> feat: change details > article, line-clamp, CSS Stylings

- src/views/WishList.vue
Feedback vorhanden. Fehler kann immernoch auftreten :C
> Feat: VoteFeedback

- src/components/QrCodeGenerator2.vue
- src/views/dj/CreateEvent.vue
- src/views/dj/EditEvent.vue
Hab die ganze QR Code Anzeige mal gepimpt!
> 284 qr code überarbeiten

- src/views/guest/GuestStart.vue
wenn event inaktiv ist bekommt gast sweetalert meldung
> feat: sweetalert bei guest start
